language: cpp
sudo: false
compiler:
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - gcc-5
      - g++-5
      - libstdc++-5-dev
      - liblua5.1-0-dev
      - python-virtualenv
    sources:
      - ubuntu-toolchain-r-test
before_script:
 - wget http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium-dev_1.0.3-1_amd64.deb http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium13_1.0.3-1_amd64.deb
 - dpkg-deb -x libsodium13_1.0.3-1_amd64.deb libsodium
 - dpkg-deb -x libsodium-dev_1.0.3-1_amd64.deb libsodium
 - sed -i -e "s@/usr@$(pwd)/libsodium/usr@" libsodium/usr/lib/x86_64-linux-gnu/pkgconfig/libsodium.pc
script:
 - export CC='gcc-5' CXX='g++-5'
 - autoreconf -i
 - PKG_CONFIG_PATH=$(pwd)/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig ./configure
 - make
 - cd regression-tests
 - ./runtests
 - git status
 - git status | grep -q clean
notifications:
  irc:
    channels:
      - "irc.oftc.net#dovepower"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
