language: cpp
sudo: false
compiler:
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - gcc-5
      - g++-5
      - libstdc++-5-dev
      - liblua5.1-0-dev
      - libsodium-dev
      - python-virtualenv
    sources:
      - ubuntu-toolchain-r-test
before_script:
script:
 - dpkg -L python-virtualenv
 - export CC='gcc-5' CXX='g++-5'
 - autoreconf -i
 - ./configure
 - make
 - cd regression-tests
 - ./runtests
 - git status
 - git status | grep -q clean
notifications:
  irc:
    channels:
      - "irc.oftc.net#dovepower"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
